/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class Admin_login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_login
     */
    String acc_type;
    
    char  choice;
     int xmouse;
       int ymouse;
     Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public Admin_login() {
        initComponents();
        con=Connectpro.dbconnect();
        Color c = new Color(43,43,43);
        this.getContentPane().setBackground(c);
        this.setSize(1024,708);
    }
         public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_pass = new javax.swing.JPasswordField();
        username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 148, 29));
        jLabel1.setText("ADMIN LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 411, 71);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 148, 29));
        jLabel2.setText("Username  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 250, 127, 25);

        t_user.setBackground(new java.awt.Color(43, 43, 43));
        t_user.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        t_user.setForeground(new java.awt.Color(247, 148, 29));
        t_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        t_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_userActionPerformed(evt);
            }
        });
        getContentPane().add(t_user);
        t_user.setBounds(280, 250, 216, 33);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 148, 29));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 330, 112, 33);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 148, 29));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/login.jpg"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 410, 140, 40);

        t_pass.setBackground(new java.awt.Color(43, 43, 43));
        t_pass.setForeground(new java.awt.Color(247, 148, 29));
        t_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });
        getContentPane().add(t_pass);
        t_pass.setBounds(280, 330, 216, 33);
        getContentPane().add(username);
        username.setBounds(440, 150, 0, 0);
        getContentPane().add(pass);
        pass.setBounds(420, 180, 0, 0);

        jLabel5.setForeground(new java.awt.Color(43, 43, 43));
        jLabel5.setText("jLabel4");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(4, 0, 920, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(960, 0, 20, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(990, 0, 20, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(770, 540, 257, 168);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 20, 507, 136);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_userActionPerformed

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if((t_user.getText().equals(""))||(t_pass.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Please enter the username and password","Admin Login",2);
        }
        else
        {
            try {
                username.setText(t_user.getText());
                pass.setText(t_pass.getText());
                String a = "Admin";
                String sql="Select * from accdetails where username=? and password=? and accestype='"+a+"'" ;
                ps=con.prepareStatement(sql);
                ps.setString(1,t_user.getText() );
                ps.setString(2,t_pass.getText() );
                
                
                rs=ps.executeQuery();
                
                if(rs.next())
                
                    //these are the labels..where username and pass ll b retrieved
                    //check whether the username and pass label values are the admin username or pass or not
                    //retrieve the access type in a variable "String acc_type"
                    //acc_type is declared above use that variable to fetch access type
                    //dnt run it yet...some changes have to be made when i come there
                    //if(acc_type.equals("Admin"))
                    {
                        JOptionPane.showMessageDialog(null,"Admin user authenticated","Admin authentication",1);
                        
                       // if(choice=='m')
                       // {
                          
                            RegisterAccGUI r = new RegisterAccGUI();
                             r.setVisible(true);
                            this.dispose();
                            ps.close();
                            rs.close();
                       // }
                        
                        //if(choice=='b')
                       // {
                            //buildin_details b = new buildin_details();
                            // b.setVisible(true);
                           // close();
                        //}
                        
                    }
                    
                    else if(acc_type.equals(""))
                    {
                        JOptionPane.showMessageDialog(null," User Account does not exist ","Admin Authentication",0);
                    }
                    
                    else if(acc_type.equals("Receptionist"))
                    {
                        JOptionPane.showMessageDialog(null," User Account is a Receptionist Account  ","Admin Authentication",0);
                    }} catch (SQLException ex) {
                Logger.getLogger(Admin_login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
       int xmouse=evt.getX();
       int ymouse=evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        // TODO add your handling code here:
 
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(LoginGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    public void recieveChar(char x)
    {
      choice = x;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_user;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
