package the.register;


import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows
 */
public class BuildinDetailsGUI extends javax.swing.JFrame {

    /**
     * Creates new form BuildinDetailsGUI
     */
    Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
        
    int x;
    Object w;
    int xmouse;
    int ymouse;
    public BuildinDetailsGUI() {
        initComponents();
          con=Connectpro.dbconnect();
        Color c = new Color(43,43,43);
        this.getContentPane().setBackground(c);
       
        x = Wings.getItemCount();
    }
 public  void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Building_name = new javax.swing.JLabel();
        t_buildingname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_sec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Wings = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        nofwings = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_buildingname2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 43, 43));
        setMinimumSize(new java.awt.Dimension(1024, 715));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Building_name.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Building_name.setForeground(new java.awt.Color(247, 148, 29));
        Building_name.setText(" Building Name :");
        getContentPane().add(Building_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 201, 130, -1));

        t_buildingname.setBackground(new java.awt.Color(43, 43, 43));
        t_buildingname.setForeground(new java.awt.Color(247, 148, 29));
        t_buildingname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29)));
        t_buildingname.setCaretColor(new java.awt.Color(247, 148, 29));
        t_buildingname.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(t_buildingname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 176, 28));

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 148, 29));
        jLabel2.setText("Number of Wings :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 150, -1));

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 148, 29));
        jLabel3.setText("Name of Secretary : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, -1));

        t_sec.setBackground(new java.awt.Color(43, 43, 43));
        t_sec.setForeground(new java.awt.Color(247, 148, 29));
        t_sec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29)));
        t_sec.setCaretColor(new java.awt.Color(247, 148, 29));
        t_sec.setSelectionColor(new java.awt.Color(247, 148, 29));
        t_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_secActionPerformed(evt);
            }
        });
        getContentPane().add(t_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 176, 28));

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 148, 29));
        jLabel4.setText("Name of Chairman :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 160, -1));

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 148, 29));
        jLabel5.setText("Enter the details of your building here :-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 330, -1));

        Wings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WingsActionPerformed(evt);
            }
        });
        getContentPane().add(Wings, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 50, -1));

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 148, 29));
        jLabel6.setText("Select your Wing :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 150, -1));

        Submit.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(247, 148, 29));
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/submit.jpg"))); // NOI18N
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 447, 140, -1));

        nofwings.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        nofwings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nofwingsMouseEntered(evt);
            }
        });
        nofwings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofwingsActionPerformed(evt);
            }
        });
        getContentPane().add(nofwings, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 50, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 110, 20));
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        t_buildingname2.setBackground(new java.awt.Color(43, 43, 43));
        t_buildingname2.setForeground(new java.awt.Color(247, 148, 29));
        t_buildingname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29)));
        t_buildingname2.setCaretColor(new java.awt.Color(247, 148, 29));
        t_buildingname2.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(t_buildingname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 176, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_secActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        if((t_buildingname.getText().equals("")||(t_buildingname2.getText().equals(""))||(t_sec.getText().equals("")))||Wings.getSelectedItem()==null)
                {
                    JOptionPane.showMessageDialog(null,"Please Enter all the fields","Building Details",1);
                }
        else
        {
            int choice = JOptionPane.showConfirmDialog(null,"Have you entered the details properly ?","Building details ", JOptionPane.YES_NO_CANCEL_OPTION,3);
            if(choice==0)
            {
                try {
                    // code for transfering data to database
                    String sql="Insert into building(name) values(?)";
                    ps=con.prepareStatement(sql);
                    ps.setString(1, t_buildingname.getText());
                    ps.execute();
                    JOptionPane.showMessageDialog(null,"DATA IS ENTERED");
                    ps.close();
                    rs.close();
                     LoginGUI l = new LoginGUI();
                    l.setVisible(true);
                    close();
                    dispose();
                    
//Uncomment this ------->>>>>>//
                   
                } catch (SQLException ex) {
                    Logger.getLogger(BuildinDetailsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_SubmitMouseClicked

    private void WingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WingsActionPerformed

    private void nofwingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofwingsActionPerformed
        // TODO add your handling code here:
         Wings.removeAllItems();//Removing all items for selecting nxt number of wings
         
         int wings = nofwings.getSelectedIndex()+1;
    
        wings=wings+65;
       for(int i  = 65;i<wings;i++)
       {
           char wing_name = (char)i;//converting  number to characters
           Wings.addItem(wing_name);
       }
//       nofwings.setEnabled(false);
       
     
        
    }//GEN-LAST:event_nofwingsActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void nofwingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nofwingsMouseEntered
        // TODO add your handling code here:
    
    }//GEN-LAST:event_nofwingsMouseEntered

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null,"Do you really want to logout ?","Logout", JOptionPane.YES_NO_OPTION,3, null);

        if(choice==0)
        {
            close();
            LoginGUI l = new LoginGUI();
            l.setLocation(470, 180);
            l.setVisible(true);
            close();
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildinDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildinDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildinDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildinDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildinDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Building_name;
    private javax.swing.JLabel Submit;
    private javax.swing.JComboBox Wings;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel menu;
    private javax.swing.JComboBox nofwings;
    private javax.swing.JTextField t_buildingname;
    private javax.swing.JTextField t_buildingname2;
    private javax.swing.JTextField t_sec;
    // End of variables declaration//GEN-END:variables
}
