/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class CreateAccGUI extends javax.swing.JFrame {
char check;
    /**
     * Creates new form CreateAccGUI
     1;
    public Create*/
    Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public CreateAccGUI() {
        initComponents();
        con=Connectpro.dbconnect();
       
    }

      public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
      public void receiveTitle(String s)
      {
          setTitle(s);
      }
      public void recieveLabel(String s)
      {
          TopLabel.setText(s);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TopLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_adminPass = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Password");
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        TopLabel.setText("Enter the Admin Password");

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\download (1).jpg")); // NOI18N

        txt_adminPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_adminPassFocusGained(evt);
            }
        });

        ok.setText("OK");
        ok.setFocusCycleRoot(true);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ok)
                        .addGap(28, 28, 28)
                        .addComponent(Cancel)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ok)
                            .addComponent(Cancel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
    try {
        LoginGUI l = new LoginGUI();
        String acs= "Admin";
        String sql="Select * from accdetails where accestype='"+acs+"'and password=? ";
        
        ps=con.prepareStatement(sql);
        ps.setString(1,txt_adminPass.getText() );
        rs=ps.executeQuery();
                if(rs.next())
                {
                     rs.close();
                    ps.close();
                    ManageAccGUI m = new ManageAccGUI();
                    
                    if(check=='d')
                    {
                        
                        DeleteAccGUI d = new DeleteAccGUI();
                        close();
                        d.setLocation(470,180);
                        d.setVisible(true);
                    }
                    else if(check=='e')
                    {
                        EditAccGUI e = new EditAccGUI();
                        close();
                        
                        e.setLocation(470,180);
                        e.setVisible(true);
                        
                    }
                    else if(check=='u')
                    {
                        UpgradeAccGUI u = new UpgradeAccGUI();
                        close();
                        u.setLocation(470,180);
                        u.setVisible(true);
                    }
                    
                    else
                    {
                         rs.close();
                        ps.close();
                        RegisterAccGUI r = new RegisterAccGUI();
                        
                        r.setLocation(470,180);
                        r.setSize(480, 390);
                        
                        r.setVisible(true);
                        close();
                    }
                }
                else
                {
                    
                    if(check=='e')
                    {
                        JOptionPane.showMessageDialog(null,"Invalid password","New Account Creation",0);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Invalid admin password","New Account Creation",0);
                    }
                    close();
                    ManageAccGUI m = new ManageAccGUI();
                    m.setLocation(470,180);
                    m.setVisible(true);
                      
                    close();
                    
                }
    } catch (SQLException ex) {
        Logger.getLogger(CreateAccGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    finally
    {
        try {
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(CreateAccGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_okActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        close();
       ManageAccGUI m = new ManageAccGUI();
       m.setLocation(470,180);
       m.setSize(438, 310);
        m.setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void txt_adminPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_adminPassFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adminPassFocusGained

    public void recieveChar(char c)
    {
        check = c;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel TopLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField txt_adminPass;
    // End of variables declaration//GEN-END:variables
}
