/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class DeleteAccGUI extends javax.swing.JFrame {

    /**
     * Creates new form DeleteAccGUI
     */
    int xmouse;
    int ymouse;
    int cnt=0;
    Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public DeleteAccGUI() {
        initComponents();
            
        Color c=new Color( 43,43,43);
       this.getContentPane().setBackground(c);
       //menu.setVisible(false);
       con=Connectpro.dbconnect();
    }
  public  void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        User_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        delete_acc = new javax.swing.JLabel();
        bacK = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Account");
        setBackground(new java.awt.Color(43, 43, 43));
        setMinimumSize(new java.awt.Dimension(1024, 708));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1014, 11, 0, 0);

        jLabel2.setBackground(new java.awt.Color(43, 43, 43));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 148, 29));
        jLabel2.setText("Enter The Details of the Account you want to Delete : -");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 200, 460, 22);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 148, 29));
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 310, 140, 40);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 148, 29));
        jLabel4.setText("User ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 400, 170, 49);

        Name.setBackground(new java.awt.Color(43, 43, 43));
        Name.setForeground(new java.awt.Color(247, 148, 29));
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        Name.setCaretColor(new java.awt.Color(43, 43, 43));
        Name.setSelectionColor(new java.awt.Color(247, 148, 29));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(260, 310, 260, 37);

        User_id.setBackground(new java.awt.Color(43, 43, 43));
        User_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        User_id.setForeground(new java.awt.Color(247, 148, 29));
        User_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        User_id.setCaretColor(new java.awt.Color(247, 148, 29));
        User_id.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(User_id);
        User_id.setBounds(260, 400, 260, 37);

        jLabel5.setBackground(new java.awt.Color(43, 43, 43));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 148, 29));
        jLabel5.setText("OR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 360, 40, 30);

        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(223, 189, 0, 0);

        delete_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/delete.jpg"))); // NOI18N
        delete_acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_accMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_accMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delete_accMouseExited(evt);
            }
        });
        delete_acc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                delete_accMouseMoved(evt);
            }
        });
        getContentPane().add(delete_acc);
        delete_acc.setBounds(320, 490, 140, 43);

        bacK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/back.jpg"))); // NOI18N
        bacK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bacK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bacKMouseClicked(evt);
            }
        });
        getContentPane().add(bacK);
        bacK.setBounds(30, 610, 70, 60);

        jLabel6.setBackground(new java.awt.Color(43, 43, 43));
        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 65)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 148, 29));
        jLabel6.setText("DELETE ACCOUNT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 30, 570, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(760, 520, 257, 168);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 0, 20, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(940, 0, 20, 20);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1020, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 20, 507, 136);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_backMouseClicked

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        
    }//GEN-LAST:event_deleteMouseClicked

    private void delete_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_accMouseClicked
        // TODO add your handling code here:
          if((Name.getText().equals(""))&&(User_id.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Enter any of the above fields","Delete Account",2);
        }
        else
        {
          
            //Delete Account Query here !
           int choice = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO DELETE","Delete Account",JOptionPane.YES_NO_OPTION,3, null);
           
            if(choice==0)
            {
               try {
                   String sql="delete from accdetails where name=? and username=?";
                   ps=con.prepareStatement(sql);
                   ps.setString(1, Name.getText());
                   ps.setString(2, User_id.getText());
                   ps.execute();
                   JOptionPane.showMessageDialog(null,"Account deleted !","Delete Account" ,1);
                   ManageAccGUI m = new ManageAccGUI();
                   close();
                   m.setLocation(470,180);
                   m.setVisible(true);
               } catch (SQLException ex) {
                   Logger.getLogger(DeleteAccGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            
        }
    }//GEN-LAST:event_delete_accMouseClicked

    private void bacKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bacKMouseClicked
        // TODO add your handling code here:
               int choice = JOptionPane.showConfirmDialog(null,"Do you really want to go back","Delete Account",JOptionPane.YES_NO_OPTION,3, null);  
        if(choice==0)
        {
        ManageAccGUI m = new ManageAccGUI();
           close();
           m.setLocation(470,180);
            m.setSize(438, 310);
           m.setVisible(true);
        }
    }//GEN-LAST:event_bacKMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void delete_accMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_accMouseMoved
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_delete_accMouseMoved

    private void delete_accMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_accMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/Labels/delete_hover.jpg"));
        delete_acc.setIcon(i);
    }//GEN-LAST:event_delete_accMouseEntered

    private void delete_accMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_accMouseExited
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/Labels/delete.jpg"));
        delete_acc.setIcon(i);
    }//GEN-LAST:event_delete_accMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAccGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField User_id;
    private javax.swing.JLabel bacK;
    private javax.swing.JLabel back;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel delete_acc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
