/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.event.WindowEvent;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Windows
 */
 
public class LoginGUI extends javax.swing.JFrame {

    private static void setIcon(ImageIcon i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form LoginGUI
     */
    String u_name,pass ;
    int count;
  boolean visible;
             int  xmouse;
        int ymouse;
        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public LoginGUI() {
        initComponents();
            con=Connectpro.dbconnect();
          //ResetPassword.setForeground(Color.BLUE);
     
        Color c=new Color(43,43,43);
  
       this.getContentPane().setBackground(c);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public  void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();
        ResetPassword = new javax.swing.JLabel();
        TopLabel = new javax.swing.JLabel();
        log_in = new javax.swing.JLabel();
        bacK = new javax.swing.JLabel();
        getacctype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        create_acc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(1030, 737));
        setName("Login Page"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txt_username.setBackground(new java.awt.Color(43, 43, 43));
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 153, 0));
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 153, 0));
        txt_username.setOpaque(false);
        txt_username.setSelectionColor(new java.awt.Color(255, 153, 0));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username);
        txt_username.setBounds(450, 350, 260, 37);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(1418, 11, 0, 0);

        txt_password.setBackground(new java.awt.Color(43, 43, 43));
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 153, 51));
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 153, 0));
        txt_password.setOpaque(false);
        txt_password.setSelectionColor(new java.awt.Color(255, 153, 0));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password);
        txt_password.setBounds(450, 420, 260, 40);

        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(1097, 105, 0, 29);

        ResetPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ResetPassword.setForeground(new java.awt.Color(255, 153, 51));
        ResetPassword.setText("Reset Password ?");
        ResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(ResetPassword);
        ResetPassword.setBounds(500, 597, 128, 20);

        TopLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopLabelMouseClicked(evt);
            }
        });
        getContentPane().add(TopLabel);
        TopLabel.setBounds(1001, 0, 259, 30);

        log_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/login.jpg"))); // NOI18N
        log_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_inMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_inMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_inMouseExited(evt);
            }
        });
        getContentPane().add(log_in);
        log_in.setBounds(490, 519, 140, 40);

        bacK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/register/go-back.png"))); // NOI18N
        bacK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bacK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bacKMouseClicked(evt);
            }
        });
        getContentPane().add(bacK);
        bacK.setBounds(1382, 11, 30, 30);
        getContentPane().add(getacctype);
        getacctype.setBounds(574, 140, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(990, 0, 20, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(960, 0, 20, 20);

        jLabel4.setForeground(new java.awt.Color(43, 43, 43));
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, 0, 920, 20);

        jLabel5.setBackground(new java.awt.Color(43, 43, 43));
        jLabel5.setForeground(new java.awt.Color(243, 148, 29));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(900, 30, 120, 20);

        jLabel6.setBackground(new java.awt.Color(43, 43, 43));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(900, 90, 110, 20);

        create_acc.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        create_acc.setForeground(new java.awt.Color(247, 148, 29));
        create_acc.setText("Create Account.");
        create_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_accMouseClicked(evt);
            }
        });
        getContentPane().add(create_acc);
        create_acc.setBounds(870, 160, 130, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(774, 258, 250, 480);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 148, 29));
        jLabel7.setText("USERNAME:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 350, 140, 50);

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 148, 29));
        jLabel8.setText("PASSWORD:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 430, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_LoginMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_BackMouseClicked

    private void ResetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetPasswordMouseClicked
        // TODO add your handling code here:
    
        ResetPassGUI r = new ResetPassGUI();
        r.receiveCharReset('l');
         r.setLocation(470,180);
        r.setVisible(true);
        close();
     
    
    }//GEN-LAST:event_ResetPasswordMouseClicked

  
    private void log_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_inMouseClicked
        try {
            // TODO add your handling code here:
            String sql="Select * from accdetails where username=? and password=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_username.getText() );
            ps.setString(2,txt_password.getText() );
           
                    
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                String add2 = rs.getString("accestype");
               getacctype.setText(add2);
               
               if(add2.equals("Receptionist"))
               {
                   ManageAccGUI m1 = new ManageAccGUI();
                   m1.getAccess(add2);
               }
                MainGUI m1 = new MainGUI();
                m1.getAccess(add2);
                
                
                JOptionPane.showMessageDialog(null,"Login Successful","Authentication",1);
            
            
                 
                  m1.user_nameRecieve(txt_username.getText());
              m1.setVisible(true);
             
             if(visible==false)
               {
                  this.dispose();
                   this.setVisible(false);
                   close();
                   //m1.setVisible(true);
               }
              
            }
            else if(txt_username.getText().equals("")||txt_password.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please enter the Username and Password ","Authentication",2);
              
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password ","Authentication",0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
                    {
                        
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }       
    }//GEN-LAST:event_log_inMouseClicked

    private void bacKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bacKMouseClicked
        // TODO add your handling code here:
               FirstScreenGUI f = new FirstScreenGUI();
        close();
        f.setLocation(470,180);
        f.setVisible(true);
    }//GEN-LAST:event_bacKMouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(LoginGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void log_inMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_inMouseEntered
        // TODO add your handling code here:
        ImageIcon i1 = new ImageIcon(getClass().getResource("/Labels/login_hover.png"));
        log_in.setIcon(i1);
        
    }//GEN-LAST:event_log_inMouseEntered

    private void log_inMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_inMouseExited
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/Labels/login.jpg"));
        log_in.setIcon(i);
    }//GEN-LAST:event_log_inMouseExited

    private void TopLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopLabelMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TopLabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
             xmouse=evt.getX();
         ymouse=evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
      
         int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
       RegisterAccGUI r = new RegisterAccGUI();
       r.setVisible(true);
        close();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         ManageAccGUI m = new ManageAccGUI();
       m.setVisible(true);
        close();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void create_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_accMouseClicked
        // TODO add your handling code here:
        Admin_login a = new Admin_login();
        a.setVisible(true);
        close();
    }//GEN-LAST:event_create_accMouseClicked

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try {
                String sql="Select * from accdetails where username=? and password=?";
                ps=con.prepareStatement(sql);
                ps.setString(1,txt_username.getText() );
                ps.setString(2,txt_password.getText() );
                
                
                rs=ps.executeQuery();
                
                if(rs.next())
                {
                    try {
                        String add2 = rs.getString("accestype");
                        getacctype.setText(add2);
                        MainGUI m1 = new MainGUI();
                        m1.getAccess(add2);
                        
                        
                        JOptionPane.showMessageDialog(null,"Login Successful","Authentication",1);
                      
                        m1.setVisible(true);
                        close();
                        rs.close();
                        ps.close();
                        
                        
                        m1.user_nameRecieve(txt_username.getText());
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password ","Authentication",0);
            }
            } catch (SQLException ex) {
                Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(5000);
                    new LoginGUI().setVisible(true);
                    LoginGUI l = new LoginGUI();
                    l.setTitle("Login");
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel ResetPassword;
    private javax.swing.JLabel TopLabel;
    private javax.swing.JLabel bacK;
    private javax.swing.JLabel create_acc;
    private javax.swing.JLabel getacctype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel log_in;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
