/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Windows
 */
public class MainGUI extends javax.swing.JFrame {
char c;
int len;
int xmouse;
    int ymouse;
    
    /**
     * Creates new form MainGUI
     */
        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public MainGUI() {
        initComponents();
        con=Connectpro.dbconnect();
        jTextArea1.setVisible(false);
        Color c=new Color(43,43,43);
       // manage.setEnabled(false);
       // b_details.setEnabled(false);
       // jLabel14.setEnabled(false);
      //  jLabel15.setEnabled(false);
       this.getContentPane().setBackground(c);
        Calendar cal = new GregorianCalendar();
        Calendar cal1= Calendar.getInstance();
        java.util.Date date=new java.util.Date(cal1.getTimeInMillis());
        
       
        
                int day=cal.get(Calendar.DAY_OF_MONTH);
                int month=cal.get(Calendar.MONTH);
                int year=cal.get(Calendar.YEAR);
              
                date_lbl.setText(day+"/"+month+"/"+year);
                
                
                
                int hour=cal.get(Calendar.HOUR_OF_DAY);
                int mins=cal.get(Calendar.MINUTE);
                int sec=cal.get(Calendar.SECOND);
                time_lbl.setText(hour+":"+mins+":"+sec);
                jLabel2.setText(new SimpleDateFormat("MMMM").format(date));
                update_data();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Search = new javax.swing.JLabel();
        Insert = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        delete_multiple = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        search_record = new javax.swing.JLabel();
        insert_record = new javax.swing.JLabel();
        delete_record = new javax.swing.JLabel();
        log_out = new javax.swing.JLabel();
        delete_mul = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        time_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        user_login = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_s_Name = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Age1 = new javax.swing.JLabel();
        Number1 = new javax.swing.JLabel();
        f_where1 = new javax.swing.JLabel();
        t_where1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combobox_month = new javax.swing.JComboBox();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_number = new javax.swing.JTextField();
        txt_fwhere = new javax.swing.JTextField();
        txt_twhere = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        to_excel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        settings = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        b_details = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_purpose = new javax.swing.JTextField();

        logout.setText("Logout");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1379, 717));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(690, 190, 660, 340);

        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(294, 136, 0, 0);

        Insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertMouseClicked(evt);
            }
        });
        getContentPane().add(Insert);
        Insert.setBounds(119, 433, 0, 0);

        Delete.setToolTipText("Delete a Single Record");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(279, 433, 0, 0);

        delete_multiple.setToolTipText("Delete the records of a Month");
        delete_multiple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_multiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_multipleMouseClicked(evt);
            }
        });
        getContentPane().add(delete_multiple);
        delete_multiple.setBounds(387, 591, 0, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(296, 154, 67, 0);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(339, 154, 44, 0);

        jSeparator1.setBackground(new java.awt.Color(43, 43, 43));
        jSeparator1.setForeground(new java.awt.Color(247, 148, 29));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 80, 321, 16);

        jSeparator2.setBackground(new java.awt.Color(43, 43, 43));
        jSeparator2.setForeground(new java.awt.Color(247, 148, 29));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 570, 373, 10);

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1325, 697, 0, 0);

        search_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/search.jpg"))); // NOI18N
        search_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_recordMouseClicked(evt);
            }
        });
        getContentPane().add(search_record);
        search_record.setBounds(34, 89, 140, 43);

        insert_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/insert.jpg"))); // NOI18N
        insert_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insert_recordMouseClicked(evt);
            }
        });
        getContentPane().add(insert_record);
        insert_record.setBounds(30, 510, 140, 43);

        delete_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/delete.jpg"))); // NOI18N
        delete_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_recordMouseClicked(evt);
            }
        });
        getContentPane().add(delete_record);
        delete_record.setBounds(200, 510, 140, 43);

        log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/logout.jpg"))); // NOI18N
        log_out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_outMouseClicked(evt);
            }
        });
        getContentPane().add(log_out);
        log_out.setBounds(810, 610, 140, 43);

        delete_mul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/delete.jpg"))); // NOI18N
        delete_mul.setToolTipText("Delete records for a Month");
        delete_mul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_mul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_mulMouseClicked(evt);
            }
        });
        getContentPane().add(delete_mul);
        delete_mul.setBounds(290, 640, 140, 43);

        date_lbl.setForeground(new java.awt.Color(247, 148, 29));
        getContentPane().add(date_lbl);
        date_lbl.setBounds(200, 420, 109, 26);

        time_lbl.setForeground(new java.awt.Color(247, 148, 29));
        getContentPane().add(time_lbl);
        time_lbl.setBounds(210, 460, 103, 23);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(163, 548, 0, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/print.jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 29));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 29));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 510, 140, 50);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 640, 73, 23);

        user_login.setBackground(new java.awt.Color(43, 43, 43));
        user_login.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        user_login.setForeground(new java.awt.Color(247, 148, 29));
        user_login.setText("USER LOGGED IN : ");
        getContentPane().add(user_login);
        user_login.setBounds(50, 40, 228, 14);

        jLabel9.setBackground(new java.awt.Color(43, 43, 43));
        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 148, 29));
        jLabel9.setText("NAME   :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 60, 228, 20);

        txt_s_Name.setBackground(new java.awt.Color(43, 43, 43));
        txt_s_Name.setForeground(new java.awt.Color(247, 148, 29));
        txt_s_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_s_Name.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_s_Name.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_s_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_s_NameActionPerformed(evt);
            }
        });
        txt_s_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_s_NameKeyReleased(evt);
            }
        });
        getContentPane().add(txt_s_Name);
        txt_s_Name.setBounds(190, 100, 180, 30);

        Name.setBackground(new java.awt.Color(43, 43, 43));
        Name.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(247, 148, 29));
        Name.setText("Name");
        getContentPane().add(Name);
        Name.setBounds(120, 170, 50, 19);

        Age1.setBackground(new java.awt.Color(43, 43, 43));
        Age1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Age1.setForeground(new java.awt.Color(247, 148, 29));
        Age1.setText("Age");
        getContentPane().add(Age1);
        Age1.setBounds(120, 210, 40, 19);

        Number1.setBackground(new java.awt.Color(43, 43, 43));
        Number1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Number1.setForeground(new java.awt.Color(247, 148, 29));
        Number1.setText("Contact - Number");
        getContentPane().add(Number1);
        Number1.setBounds(30, 250, 150, 20);

        f_where1.setBackground(new java.awt.Color(43, 43, 43));
        f_where1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        f_where1.setForeground(new java.awt.Color(247, 148, 29));
        f_where1.setText("From Where");
        getContentPane().add(f_where1);
        f_where1.setBounds(70, 290, 100, 19);

        t_where1.setBackground(new java.awt.Color(43, 43, 43));
        t_where1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        t_where1.setForeground(new java.awt.Color(247, 148, 29));
        t_where1.setText("To Where");
        getContentPane().add(t_where1);
        t_where1.setBounds(90, 330, 80, 19);

        Date.setBackground(new java.awt.Color(43, 43, 43));
        Date.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(247, 148, 29));
        Date.setText("          DATE                  :");
        getContentPane().add(Date);
        Date.setBounds(30, 420, 330, 26);

        jLabel1.setBackground(new java.awt.Color(43, 43, 43));
        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 148, 29));
        jLabel1.setText("  TIME                   :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 460, 340, 23);

        jLabel4.setBackground(new java.awt.Color(43, 43, 43));
        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 148, 29));
        jLabel4.setText("Delete Multiple Records");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 600, 186, 19);

        combobox_month.setBackground(new java.awt.Color(43, 43, 43));
        combobox_month.setForeground(new java.awt.Color(247, 148, 29));
        combobox_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        combobox_month.setBorder(null);
        combobox_month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(combobox_month);
        combobox_month.setBounds(280, 590, 170, 30);

        txt_name.setBackground(new java.awt.Color(43, 43, 43));
        txt_name.setForeground(new java.awt.Color(247, 148, 29));
        txt_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_name.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_name.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name);
        txt_name.setBounds(210, 160, 220, 30);

        txt_age.setBackground(new java.awt.Color(43, 43, 43));
        txt_age.setForeground(new java.awt.Color(247, 148, 29));
        txt_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_age.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_age.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ageKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });
        getContentPane().add(txt_age);
        txt_age.setBounds(210, 200, 60, 30);

        txt_number.setBackground(new java.awt.Color(43, 43, 43));
        txt_number.setForeground(new java.awt.Color(247, 148, 29));
        txt_number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_number.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_number.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numberKeyTyped(evt);
            }
        });
        getContentPane().add(txt_number);
        txt_number.setBounds(210, 240, 220, 30);

        txt_fwhere.setBackground(new java.awt.Color(43, 43, 43));
        txt_fwhere.setForeground(new java.awt.Color(247, 148, 29));
        txt_fwhere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_fwhere.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_fwhere.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_fwhere.setVerifyInputWhenFocusTarget(false);
        txt_fwhere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fwhereActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fwhere);
        txt_fwhere.setBounds(210, 280, 220, 30);

        txt_twhere.setBackground(new java.awt.Color(43, 43, 43));
        txt_twhere.setForeground(new java.awt.Color(247, 148, 29));
        txt_twhere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_twhere.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_twhere.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(txt_twhere);
        txt_twhere.setBounds(210, 330, 220, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1120, 550, 257, 168);

        to_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/excel.jpg"))); // NOI18N
        to_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        to_excel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_excelMouseClicked(evt);
            }
        });
        getContentPane().add(to_excel);
        to_excel.setBounds(530, 520, 140, 43);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1340, 0, 20, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1310, 0, 20, 20);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/settings1.jpg"))); // NOI18N
        settings.setToolTipText("ManageAccounts");
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        getContentPane().add(settings);
        settings.setBounds(1280, 0, 20, 20);

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1380, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(630, 570, 0, 0);

        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1030, 590, 40, 14);

        b_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_detailsMouseClicked(evt);
            }
        });
        getContentPane().add(b_details);
        b_details.setBounds(650, 110, 120, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(880, 20, 500, 136);

        jLabel14.setBackground(new java.awt.Color(43, 43, 43));
        jLabel14.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(247, 148, 29));
        jLabel14.setText("Purpose");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 390, 80, 19);

        txt_purpose.setBackground(new java.awt.Color(43, 43, 43));
        txt_purpose.setForeground(new java.awt.Color(247, 148, 29));
        txt_purpose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29)));
        txt_purpose.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_purpose.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(txt_purpose);
        txt_purpose.setBounds(210, 380, 220, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
   
    }//GEN-LAST:event_logoutActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
    
        
    }//GEN-LAST:event_SearchMouseClicked
    public void upgrde()
    {
       
    }    public void user_nameRecieve(String s)
    {
        user_login.setText(user_login.getText()+s);
    }
    public void zzzz(String s)
    {
        jLabel9.setText(jLabel9.getText()+s);
    }
    private void InsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_InsertMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_DeleteMouseClicked

    private void delete_multipleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_multipleMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_delete_multipleMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
      int choice= JOptionPane.showConfirmDialog(null,"Do you really want to logout ?","Logout", JOptionPane.YES_NO_OPTION, 3, null);
       if(choice==0)
       {
        
        LoginGUI l = new LoginGUI();
        l.setLocation(470,180);
        l.setVisible(true);
        close();
       }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_recordMouseClicked
        // TODO add your handling code here:
      //  if((txt_s_Name.getText().equals(""))||(txt_s_age.getText().equals("")))
          {
                  // JOptionPane.showMessageDialog(null,"Please enter both the search fields !","Search Record ",2);
            }
       // else
        {
           //query to search the results
           
         //   txt_s_Name.setText("");
         //  txt_s_age.setText("");
           //provide a query if no record is fund to show a message that theres no such record
        }
    }//GEN-LAST:event_search_recordMouseClicked

    private void insert_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_recordMouseClicked
        // TODO add your handling code here:
           if((txt_name.getText().equals(""))||(txt_age.getText().equals(""))||(txt_number.getText().equals(""))||txt_fwhere.getText().equals("")||(txt_twhere.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Please enter all the necessary fields of the record","Insert Record",2);
        }
        else
        {
               try {
                   String sql="Insert into data1(name,age,contact,from_where,to_where,purpose,date,time,month) values(?,?,?,?,?,?,?,?,?)";
                   ps=con.prepareStatement(sql);
                   ps.setString(1, txt_name.getText());
                   ps.setString(2, txt_age.getText());
                   ps.setString(3, txt_number.getText());
                   ps.setString(4, txt_fwhere.getText());
                   ps.setString(5, txt_twhere.getText());
                   ps.setString(6, txt_purpose.getText());
                   ps.setString(7,date_lbl.getText() );
                   ps.setString(8,time_lbl.getText() );
                   ps.setString(9,jLabel2.getText());
                  
                   ps.execute();
                   JOptionPane.showMessageDialog(null,"DATA IS ENTERED");
                   ps.close();
                   rs.close();
                   update_data();
                   txt_name.setText("");
                   txt_age.setText("");
                   txt_number.setText("");
                   txt_fwhere.setText("");
                   txt_twhere.setText("");
                   txt_purpose.setText(" ");
               } catch (SQLException ex) {
                   Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
        }
    }//GEN-LAST:event_insert_recordMouseClicked

    private void delete_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_recordMouseClicked
        // TODO add your handling code here:
              
        boolean flag1 = delete_record.isEnabled();
                
                if(flag1==true)
                {   
                     if((txt_name.getText().equals(""))||(txt_age.getText().equals(""))||(txt_number.getText().equals(""))||txt_fwhere.getText().equals("")||(txt_twhere.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Please enter all the necessary fields for deleting the record","Delete Record",2);
        }
        else
        {
            
            try {
             // TODO add your handling code here:
             int a= JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE","Delete", JOptionPane.YES_NO_OPTION);
             if(a==0)
             {
                 String sql="delete from data1 where name=? and contact=?";
             ps=con.prepareStatement(sql);
             ps.setString(1, txt_name.getText());
             ps.setString(2, txt_number.getText());
             ps.execute();
             JOptionPane.showMessageDialog(null,"DELETED");
             update_data();
             }    
             }
             catch(HeadlessException | SQLException e)
         {
            JOptionPane.showMessageDialog(null," e"); 
         }
        }
                }
    }//GEN-LAST:event_delete_recordMouseClicked

        private void update_data()
    {
            try {
                String sql="SELECT * from data1";
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
            } catch (SQLException ex) {
                
            }
           
    }
    private void log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseClicked
        // TODO add your handling code here:
          int choice = JOptionPane.showConfirmDialog(null,"Do you really want to logout ?","Logout", JOptionPane.YES_NO_OPTION,3, null);
        
          if(choice==0)
         {
       close();
        LoginGUI l = new LoginGUI();
        l.setLocation(470, 180);
        l.setVisible(true);
        close();
                  }
    }//GEN-LAST:event_log_outMouseClicked

    private void delete_mulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_mulMouseClicked
        // TODO add your handling code here:
         //query for selecting the month and deleting the record
        
             // TODO add your handling code here:
            
        boolean flag = delete_mul.isEnabled();
        
        if(flag==true)
        {
        int a= JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE","Delete", JOptionPane.YES_NO_OPTION);
             if(a==0)
             {
                 try {
                     
                     String sql="delete from data1 where month=?";
                     ps=con.prepareStatement(sql);
                     //code to get value from combobox XD
                     String value=combobox_month.getSelectedItem().toString();
                     ps.setString(1, value);
                     ps.execute();
                     JOptionPane.showMessageDialog(null,"DELETED");
                     update_data();
                 } catch (SQLException ex) {
                     Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }    
        }
            
        
        
    }//GEN-LAST:event_delete_mulMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try
        {
                int row = jTable1.getSelectedRow();
                String table_click=(jTable1.getModel().getValueAt(row, 0).toString());
                String table_click1=(jTable1.getModel().getValueAt(row, 2).toString());
                String sql="select * from data1 where name='"+table_click+"' and contact='"+table_click1+"' ";
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();
                if(rs.next())
                {
                        String add1 = rs.getString("name");
                        txt_name.setText(add1);
                        String add2 = rs.getString("age");
                        txt_age.setText(add2);
                        String add3 = rs.getString("contact");
                        txt_number.setText(add3);
                        String add4 = rs.getString("from_where");
                        txt_fwhere.setText(add4);
                        String add5 = rs.getString("to_where");
                        txt_twhere.setText(add5);
                        String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);
                        
                }
        }
        catch(SQLException e)
        {
        }
        
        
         
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    try {
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report");
        
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        
        jTable1.print(JTable.PrintMode.NORMAL, header, footer);
    } catch (PrinterException ex) {
        Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
    try {
      //  jTextArea1.setEnabled(true);
        String a="Name: ";
        String b=txt_name.getText();
        String d = a.concat(b);
        String date_s="Date: ";
        String date =date_lbl.getText();
        String datec = date_s.concat(date);
        String places="Place: ";
        String place=txt_twhere.getText();
        String placec= places.concat(place);
        String times="Time: ";
        String time=time_lbl.getText();
        String timec=times.concat(time);
                jTextArea1.setText("\t"+d+"\n\n\t"+placec+"\n\n\t"+datec+"\n\n\t"+timec+"\n\n\n\t(person)\t\t\t(Gatekeeper)");
        MessageFormat header = new MessageFormat("GatePass");
        
        MessageFormat footer = new MessageFormat("No{0,number,integer}");
       
        jTextArea1.print(header,footer);
        
    } catch (PrinterException ex) {
        Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_s_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_s_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_s_NameActionPerformed

    private void txt_s_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_s_NameKeyReleased
        // TODO add your handling code here:
        //name
        try {
            // TODO add your handling code here:
            String sql="select*from data1 where name=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_s_Name.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                String add2 = rs.getString("age");
                txt_age.setText(add2);
                String add3 = rs.getString("contact");
                txt_number.setText(add3);
                String add4 = rs.getString("From_where");
                txt_fwhere.setText(add4);
                String add5 = rs.getString("To_where");
                txt_twhere.setText(add5);
               String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);

            }

        }
        catch(SQLException e)
        {

        }
        //age
        try {
            // TODO add your handling code here:
            String sql="select*from data1 where age=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_s_Name.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                String add2 = rs.getString("age");
                txt_age.setText(add2);
                String add3 = rs.getString("contact");
                txt_number.setText(add3);
                String add4 = rs.getString("From_where");
                txt_fwhere.setText(add4);
                String add5 = rs.getString("To_where");
                txt_twhere.setText(add5);
                String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);
            }

        }
        catch(SQLException e)
        {

        }
        // Contact

        try {
            // TODO add your handling code here:
            String sql="select*from data1 where contact=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_s_Name.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                String add2 = rs.getString("age");
                txt_age.setText(add2);
                String add3 = rs.getString("contact");
                txt_number.setText(add3);
                String add4 = rs.getString("From_where");
                txt_fwhere.setText(add4);
                String add5 = rs.getString("To_where");
                txt_twhere.setText(add5);
                String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);

            }

        }
        catch(SQLException e)
        {

        }
        //From where

        try {
            // TODO add your handling code here:
            String sql="select*from data1 where From_where=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_s_Name.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                String add2 = rs.getString("age");
                txt_age.setText(add2);
                String add3 = rs.getString("contact");
                txt_number.setText(add3);
                String add4 = rs.getString("From_where");
                txt_fwhere.setText(add4);
                String add5 = rs.getString("To_where");
                txt_twhere.setText(add5);
                String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);

            }

        }
        catch(SQLException e)
        {

        }
        //to where

        try {
            // TODO add your handling code here:
            String sql="select*from data1 where to_where=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,txt_s_Name.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                String add2 = rs.getString("age");
                txt_age.setText(add2);
                String add3 = rs.getString("contact");
                txt_number.setText(add3);
                String add4 = rs.getString("From_where");
                txt_fwhere.setText(add4);
                String add5 = rs.getString("To_where");
                txt_twhere.setText(add5);
                String add6 = rs.getString("purpose");
                        txt_purpose.setText(add6);

            }

        }
        catch(SQLException e)
        {

        }
    }//GEN-LAST:event_txt_s_NameKeyReleased

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_ageKeyPressed

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped
        // TODO add your handling code here:
        c = evt.getKeyChar();
        len = txt_age.getText().length();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
        if(len>=2)
        {
            evt.consume();
        }

    }//GEN-LAST:event_txt_ageKeyTyped

    private void txt_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numberKeyTyped
        // TODO add your handling code here:
        c = evt.getKeyChar();
        len = txt_number.getText().length();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
        if(len>=10)
        {
            evt.consume();
        }

    }//GEN-LAST:event_txt_numberKeyTyped

    private void txt_fwhereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fwhereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fwhereActionPerformed

    private void to_excelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_excelMouseClicked
        // TODO add your handling code here:
        Excels es = new Excels();
      es.fillData(jTable1, new File("C:\\result.xls"));
       JOptionPane.showMessageDialog(null,"saved as Excel file");
    }//GEN-LAST:event_to_excelMouseClicked

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
     
      ManageAccGUI m = new ManageAccGUI();
      m.setVisible(true);
      close();
    }//GEN-LAST:event_settingsMouseClicked

    private void b_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_detailsMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_b_detailsMouseClicked
   //excel
   
    public void getAccess(String s )
    {
        String access = s ;
        if(access.equals("Receptionist"))
        {
            delete_record.setEnabled(false);
            delete_mul.setEnabled(false);
            combobox_month.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age1;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Insert;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Number1;
    private javax.swing.JLabel Search;
    private javax.swing.JLabel b_details;
    private javax.swing.JComboBox combobox_month;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JLabel delete_mul;
    private javax.swing.JLabel delete_multiple;
    private javax.swing.JLabel delete_record;
    private javax.swing.JLabel f_where1;
    private javax.swing.JLabel insert_record;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel log_out;
    private javax.swing.JButton logout;
    private javax.swing.JLabel search_record;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel t_where1;
    private javax.swing.JLabel time_lbl;
    private javax.swing.JLabel to_excel;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_fwhere;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_purpose;
    private javax.swing.JTextField txt_s_Name;
    private javax.swing.JTextField txt_twhere;
    private javax.swing.JLabel user_login;
    // End of variables declaration//GEN-END:variables
}
