/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows
 */
    
public class ManageAccGUI extends javax.swing.JFrame {
String userInput;
    /**
     * Creates new form ManageAccGUI
     */Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
int xmouse;
    int ymouse;
    public ManageAccGUI() {
        initComponents();
         con=Connectpro.dbconnect();
        
        Color c=new Color(43,43,43);
      
     this.getContentPane().setBackground(c);
     
            
    }
       public  void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JLabel();
        UpgrageAcc = new javax.swing.JLabel();
        EditAcc = new javax.swing.JLabel();
        DeleteAcc = new javax.swing.JLabel();
        Reset = new javax.swing.JLabel();
        bacK = new javax.swing.JLabel();
        ed_acc = new javax.swing.JLabel();
        upgrade = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Accounts");
        setBackground(new java.awt.Color(43, 43, 43));
        setForeground(java.awt.Color.red);
        setMinimumSize(new java.awt.Dimension(1024, 708));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(208, 11, 0, 0);

        UpgrageAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpgrageAcc.setLabelFor(UpgrageAcc);
        UpgrageAcc.setToolTipText("Upgrade privilege");
        UpgrageAcc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        UpgrageAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpgrageAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpgrageAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpgrageAccMouseEntered(evt);
            }
        });
        getContentPane().add(UpgrageAcc);
        UpgrageAcc.setBounds(160, 31, 0, 110);

        EditAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditAccMouseClicked(evt);
            }
        });
        getContentPane().add(EditAcc);
        EditAcc.setBounds(190, 11, 0, 110);

        DeleteAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteAccMouseExited(evt);
            }
        });
        DeleteAcc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteAccMouseMoved(evt);
            }
        });
        getContentPane().add(DeleteAcc);
        DeleteAcc.setBounds(160, 159, 0, 110);

        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(199, 271, 0, 0);

        bacK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/back.jpg"))); // NOI18N
        bacK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bacK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bacKMouseClicked(evt);
            }
        });
        getContentPane().add(bacK);
        bacK.setBounds(60, 630, 80, 40);

        ed_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/edit.jpg"))); // NOI18N
        ed_acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ed_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ed_accMouseClicked(evt);
            }
        });
        getContentPane().add(ed_acc);
        ed_acc.setBounds(140, 370, 140, 43);

        upgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/upgrade.jpg"))); // NOI18N
        upgrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upgrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeMouseClicked(evt);
            }
        });
        getContentPane().add(upgrade);
        upgrade.setBounds(740, 360, 140, 50);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/delete.jpg"))); // NOI18N
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(440, 360, 150, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(910, 540, 63, 24);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 277, 218, 199);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/manage.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 170, 1024, 340);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(770, 540, 257, 168);

        jLabel5.setBackground(new java.awt.Color(43, 43, 43));
        jLabel5.setFont(new java.awt.Font("Myriad Pro", 1, 65)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 148, 29));
        jLabel5.setText("MANAGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 370, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 0, 20, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(940, 0, 20, 20);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1020, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 20, 507, 136);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:
       ResetPassGUI r1 = new ResetPassGUI();
       r1.receiveCharReset('m');
     close();
       r1.setLocation(470,180);
       r1.setVisible(true);
      
    }//GEN-LAST:event_ResetMouseClicked

    private void DeleteAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccMouseClicked
     
    }//GEN-LAST:event_DeleteAccMouseClicked
 public void getAccess(String s1 )
    {
        String access = s1 ;
        if(access.equals("Receptionist"))
        {
            delete.setEnabled(false);
            upgrade.setEnabled(false);
            delete.setToolTipText("Accessible to Admin");
              upgrade.setToolTipText("Accessible to Admin");
        }
    }
    private void EditAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditAccMouseClicked
        // TODO add your handling code here:
          
     
    }//GEN-LAST:event_EditAccMouseClicked

    private void UpgrageAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpgrageAccMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_UpgrageAccMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_BackMouseClicked

    private void UpgrageAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpgrageAccMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UpgrageAccMouseEntered

    private void DeleteAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccMouseEntered
        // TODO add your handling code here:
         try
       {
        String imageName = "delete_reverse.jpg";
        DeleteAcc.setIcon(new ImageIcon(ImageIO.read(new File(imageName))));
       }
       catch(IOException e){}
         
    }//GEN-LAST:event_DeleteAccMouseEntered

    private void DeleteAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccMouseExited
        // TODO add your handling code here:
    
    }//GEN-LAST:event_DeleteAccMouseExited

    private void DeleteAccMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccMouseMoved
        // TODO add your handling code here:
           JLabel DeleteAcc = new JLabel();
        DeleteAcc.setIcon(new ImageIcon("E:\\delete_reverse.jpg"));
        DeleteAcc.updateUI();
    }//GEN-LAST:event_DeleteAccMouseMoved

    private void bacKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bacKMouseClicked
        // TODO add your handling code here:
            MainGUI l = new MainGUI();
        close();
        //f.setLocation(470,240);
        l.setVisible(true);
    }//GEN-LAST:event_bacKMouseClicked

    private void ed_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ed_accMouseClicked
        // TODO add your handling code here:
               LoginGUI l = new LoginGUI();
               
               ResetPassGUI r = new ResetPassGUI();
               r.receiveCharReset('m');
               r.setVisible(true);
            close();
    }//GEN-LAST:event_ed_accMouseClicked

    private void upgradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeMouseClicked
    
       
        LoginGUI l = new LoginGUI();
      UpgradeAccGUI u = new UpgradeAccGUI();
      u.setVisible(true);
      close();
        
    }//GEN-LAST:event_upgradeMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
  DeleteAccGUI d = new DeleteAccGUI();
      d.setVisible(true);
      close();
    }//GEN-LAST:event_deleteMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel DeleteAcc;
    private javax.swing.JLabel EditAcc;
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel UpgrageAcc;
    private javax.swing.JLabel bacK;
    public javax.swing.JLabel delete;
    private javax.swing.JLabel ed_acc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel upgrade;
    // End of variables declaration//GEN-END:variables
}
