/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import the.register.Connectpro;
/**
 *
 * @author Windows
 */
    
public class RegisterAccGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAccGUI
     */Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
        int xmouse,ymouse;
  
    public RegisterAccGUI() {
        initComponents();
        con = Connectpro.dbconnect();
          
        Color c=new Color(43,43,43);
  
       this.getContentPane().setBackground(c);
       
    }
  public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        txt_name = new javax.swing.JTextField();
        txt_newUser = new javax.swing.JTextField();
        r_admin = new javax.swing.JRadioButton();
        r_recpt = new javax.swing.JRadioButton();
        txt_newPass = new javax.swing.JPasswordField();
        txt_newConPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        SUBMIT = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        submit_acc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register new Account");
        setBackground(new java.awt.Color(43, 43, 43));
        setMinimumSize(new java.awt.Dimension(1024, 718));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txt_name.setBackground(new java.awt.Color(43, 43, 43));
        txt_name.setForeground(new java.awt.Color(247, 148, 29));
        txt_name.setToolTipText("");
        txt_name.setBorder(null);
        txt_name.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_name.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(txt_name);
        txt_name.setBounds(430, 200, 250, 40);

        txt_newUser.setBackground(new java.awt.Color(43, 43, 43));
        txt_newUser.setForeground(new java.awt.Color(247, 148, 29));
        txt_newUser.setBorder(null);
        txt_newUser.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_newUser.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newUserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_newUser);
        txt_newUser.setBounds(430, 280, 250, 40);

        r_admin.setBackground(new java.awt.Color(43, 43, 43));
        buttonGroup1.add(r_admin);
        r_admin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r_admin.setForeground(new java.awt.Color(247, 148, 29));
        r_admin.setSelected(true);
        r_admin.setText("Admin ");
        r_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_adminActionPerformed(evt);
            }
        });
        r_admin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r_adminFocusGained(evt);
            }
        });
        getContentPane().add(r_admin);
        r_admin.setBounds(420, 520, 78, 25);

        r_recpt.setBackground(new java.awt.Color(43, 43, 43));
        buttonGroup1.add(r_recpt);
        r_recpt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r_recpt.setForeground(new java.awt.Color(247, 148, 29));
        r_recpt.setText("Receptionist ");
        r_recpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r_recpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_recptActionPerformed(evt);
            }
        });
        getContentPane().add(r_recpt);
        r_recpt.setBounds(550, 520, 105, 25);

        txt_newPass.setBackground(new java.awt.Color(43, 43, 43));
        txt_newPass.setForeground(new java.awt.Color(247, 148, 29));
        txt_newPass.setBorder(null);
        txt_newPass.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_newPass.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newPassActionPerformed(evt);
            }
        });
        getContentPane().add(txt_newPass);
        txt_newPass.setBounds(430, 360, 250, 30);

        txt_newConPass.setBackground(new java.awt.Color(43, 43, 43));
        txt_newConPass.setForeground(new java.awt.Color(247, 148, 29));
        txt_newConPass.setBorder(null);
        txt_newConPass.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_newConPass.setSelectionColor(new java.awt.Color(247, 148, 29));
        getContentPane().add(txt_newConPass);
        txt_newConPass.setBounds(430, 450, 250, 40);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(381, 235, 247, 0);
        getContentPane().add(output);
        output.setBounds(403, 235, 0, 0);

        SUBMIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUBMITMouseClicked(evt);
            }
        });
        getContentPane().add(SUBMIT);
        SUBMIT.setBounds(220, 337, 0, 0);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(417, 49, 0, 0);

        submit_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/submit.jpg"))); // NOI18N
        submit_acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_accMouseClicked(evt);
            }
        });
        getContentPane().add(submit_acc);
        submit_acc.setBounds(380, 570, 150, 60);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 0, 20, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(940, 0, 20, 20);

        jLabel9.setBackground(new java.awt.Color(43, 43, 43));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1020, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/create account_1.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 20, 1024, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_adminActionPerformed
        // TODO add your handling code here:
        accesstype="Admin";
    }//GEN-LAST:event_r_adminActionPerformed

    private void SUBMITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMITMouseClicked
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_SUBMITMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_BackMouseClicked

    private void txt_newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newPassActionPerformed

    private void submit_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_accMouseClicked
        // TODO add your handling code here:
        
        if(txt_name.getText().equals("")||txt_newUser.getText().equals("")||txt_newPass.getText().equals("")||txt_newConPass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter all the fields ","New Account Creation",2);
        }
        
        else if(txt_newPass.getText().length()<6)
            {
                JOptionPane.showMessageDialog(null,"Password should be of minimum 6 characters","New Account Creation",2);
                txt_newPass.setText("");
                txt_newConPass.setText("");
            }
        
        
        else 
        {
            if(txt_newPass.getText().equals(txt_newConPass.getText()))
              
            {
                int choice=JOptionPane.showConfirmDialog(null,"Have you entered the details properly ?","Register Account", JOptionPane.YES_NO_OPTION,3, null);
                
                if(choice==0)
                {   
                    try {
                        String sql="Insert into accdetails(name,username,password,accestype) values(?,?,?,?)";
                        ps=con.prepareStatement(sql);
                        String s = txt_name.getText();
                        String user_ID = txt_newUser.getText();
                        String pass = txt_newPass.getText();
                        ps.setString(1, s);
                        ps.setString(2, user_ID);
                        ps.setString(3, pass);
                        ps.setString(4, accesstype);
                        ps.execute();
                        JOptionPane.showMessageDialog(null,"New Account Confirmed ","New account creatiom" ,1);
                        
                        /*txt_name.setText("");
                        txt_newUser.setText("");
                        txt_newPass.setText("");
                        txt_newConPass.setText("");*/
                        
                        //close();
                         
                        LoginGUI l = new LoginGUI();
                        l.setLocation(470,180);
                        l.setVisible(true);
                        close();
                    } catch (SQLException ex) {
                        Logger.getLogger(RegisterAccGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally
                    {
                        try {
                            rs.close();
                            ps.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(RegisterAccGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            else
            {
                
                
                JOptionPane.showMessageDialog(null,"New and Confirm Passwords do not match ","New account creation ",2);
                   txt_newPass.setText("");
                    txt_newConPass.setText("");
                
                
            }
        }
        //if(r_admin.isSelected())
        {
           // access_type = "admin";
        }
       // else
        {
           // access_type="receptionist";
        }
        
       // output.setText(access_type);
    }//GEN-LAST:event_submit_accMouseClicked

    private void r_recptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_recptActionPerformed
        // TODO add your handling code here:
        accesstype="Receptionist";
    }//GEN-LAST:event_r_recptActionPerformed

    private void r_adminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r_adminFocusGained
        // TODO add your handling code here:
             

    }//GEN-LAST:event_r_adminFocusGained

    private void txt_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newUserActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAccGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel SUBMIT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel output;
    private javax.swing.JRadioButton r_admin;
    private javax.swing.JRadioButton r_recpt;
    private javax.swing.JLabel submit_acc;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_newConPass;
    private javax.swing.JPasswordField txt_newPass;
    private javax.swing.JTextField txt_newUser;
    // End of variables declaration//GEN-END:variables
String accesstype="Admin";

}
