/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.register;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class UpgradeAccGUI extends javax.swing.JFrame {
String acc_type;
String s ;
int choice;
 int xmouse;
    int ymouse;
    /**
     * Creates new form UpgradeAccGUI
     */
    Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    public UpgradeAccGUI() {
        initComponents();
       
         
        Color c=new Color( 43,43,43);
        this.getContentPane().setBackground(c);
       con=Connectpro.dbconnect();
       
    }
  public  void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JLabel();
        Access_typeBox = new javax.swing.JComboBox();
        txt_accessType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        Update = new javax.swing.JLabel();
        submit_acc = new javax.swing.JLabel();
        bacK = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upgrade Access-Type");
        setMinimumSize(new java.awt.Dimension(1024, 708));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(1018, 11, 0, 0);

        Access_typeBox.setBackground(new java.awt.Color(43, 43, 43));
        Access_typeBox.setForeground(new java.awt.Color(247, 148, 29));
        Access_typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receptionist", "Admin" }));
        Access_typeBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        Access_typeBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Access_typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Access_typeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(Access_typeBox);
        Access_typeBox.setBounds(400, 510, 150, 30);

        txt_accessType.setBackground(new java.awt.Color(43, 43, 43));
        txt_accessType.setForeground(new java.awt.Color(247, 148, 29));
        txt_accessType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_accessType.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_accessType.setEnabled(false);
        txt_accessType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_accessTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_accessType);
        txt_accessType.setBounds(400, 430, 260, 37);

        jLabel2.setBackground(new java.awt.Color(43, 43, 43));
        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 148, 29));
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 290, 139, 49);

        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SubmitMouseMoved(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(357, 54, 0, 0);

        jLabel4.setBackground(new java.awt.Color(43, 43, 43));
        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 148, 29));
        jLabel4.setText("Access - Type :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 420, 284, 49);

        txt_Name.setBackground(new java.awt.Color(43, 43, 43));
        txt_Name.setForeground(new java.awt.Color(247, 148, 29));
        txt_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 148, 29), 2));
        txt_Name.setCaretColor(new java.awt.Color(247, 148, 29));
        txt_Name.setSelectionColor(new java.awt.Color(247, 148, 29));
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Name);
        txt_Name.setBounds(400, 300, 260, 37);

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/update.jpg"))); // NOI18N
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.setEnabled(false);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(400, 600, 140, 43);

        submit_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/submit.jpg"))); // NOI18N
        submit_acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_accMouseClicked(evt);
            }
        });
        getContentPane().add(submit_acc);
        submit_acc.setBounds(720, 290, 150, 60);

        bacK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/back.jpg"))); // NOI18N
        bacK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bacK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bacKMouseClicked(evt);
            }
        });
        getContentPane().add(bacK);
        bacK.setBounds(50, 630, 80, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/StellarLogo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(770, 540, 257, 168);

        jLabel1.setBackground(new java.awt.Color(43, 43, 43));
        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 148, 29));
        jLabel1.setText("UPGRADE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 310, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/mini.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(940, 0, 20, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labels/close.jpg"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 0, 20, 20);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1020, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\user\\My Documents\\Downloads\\gateKeeper.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 20, 507, 136);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BackMouseClicked

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void Access_typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Access_typeBoxActionPerformed
        // TODO add your handling code here:
        s = Access_typeBox.getSelectedItem().toString();
     
        txt_accessType.setText(s);
        Update.setEnabled(true);
    }//GEN-LAST:event_Access_typeBoxActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_SubmitMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
           if(s.equals(acc_type))
        {
            JOptionPane.showMessageDialog(null,"Same access type has been assigned","Update Access-Type" ,2);
         int choice=   JOptionPane.showConfirmDialog(null,"Dont you want to change your access type ?","Update Access-Type",JOptionPane.YES_NO_OPTION,3, null);
        
         if(choice==1)
         {
             ManageAccGUI m = new ManageAccGUI();
                close();
                m.setSize(438, 310);
                m.setLocation(470,180);
                m.setVisible(true);
         }
        else
         {
             Update.setEnabled(false);
             submit_acc.setEnabled(true);
         }
        }
           else
           {
               choice = JOptionPane.showConfirmDialog(null,"Have you made the right choice ?","Upgrate Access-Type",JOptionPane.YES_NO_OPTION,3, null);
               if(choice==0)
               {
                   try {
                       //query to update the access
                       String value=Access_typeBox.getSelectedItem().toString();
                       String uname=txt_Name.getText();
                       String sql="update accdetails set accestype='"+value+"' where username='"+uname+"'";
                       ps=con.prepareStatement(sql);
                       
                     
                       
                       ps.execute();
                       JOptionPane.showMessageDialog(null,"Account Access-Type upgraded","Upgrade Access_Type",1);
                       Update.setEnabled(false);
                       ManageAccGUI m = new ManageAccGUI();
                       m.setLocation(470,180);
                       m.setSize(438, 310);
                       m.setVisible(true);
                       close();
                   } catch (SQLException ex) {
                       Logger.getLogger(UpgradeAccGUI.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   
               }
               else
               {
                   Update.setEnabled(true);
               }
           }
    }//GEN-LAST:event_UpdateMouseClicked

    private void SubmitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseMoved
        // TODO add your handling code here:
      setImage("submit_reverse");
    }//GEN-LAST:event_SubmitMouseMoved

    private void submit_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_accMouseClicked
        // TODO add your handling code here:
          if(txt_Name.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the name of the user ","Update Access Privilege",2);
        }
        else
        {
              try {
                  //query to take the name to the db and retrieve its access type in the nxt txtbox
                  String sql="select * from accdetails where username=? ";
                  ps=con.prepareStatement(sql);
                  ps.setString(1, txt_Name.getText());
                  rs=ps.executeQuery();
                  if(rs.next())
                  {
                        String add1 = rs.getString("accestype");
                        txt_accessType.setText(add1);
                        submit_acc.setEnabled(false);
                  }
                      txt_Name.enable(false);
                  acc_type=txt_accessType.getText();
              } catch (SQLException ex) {
                  Logger.getLogger(UpgradeAccGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
        }
    }//GEN-LAST:event_submit_accMouseClicked

    private void bacKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bacKMouseClicked
        // TODO add your handling code here:
              int choice = JOptionPane.showConfirmDialog(null,"Do you really want to go back","Edit Account",JOptionPane.YES_NO_OPTION,3, null);  
        if(choice==0)
        {
        
        
        ManageAccGUI m = new ManageAccGUI();
           close();
           m.setLocation(470,180);
           m.setSize(438,310);
           m.setVisible(true);
        }
    }//GEN-LAST:event_bacKMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(DeleteAccGUI.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txt_accessTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_accessTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_accessTypeActionPerformed
public void setImage(String s)
{
    setIconImage(Toolkit.getDefaultToolkit().getImage(s));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpgradeAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpgradeAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpgradeAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpgradeAccGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpgradeAccGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Access_typeBox;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Submit;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel bacK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel submit_acc;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_accessType;
    // End of variables declaration//GEN-END:variables
}
